# Linux Makefile for PCRF utilities
# Try "sudo make -f Makefile.linux install" 
# (assumes that an directory /usr/local/bin exists)

# You need the following:
# - A newer version of boost (www.boost.org) (apt-get install libboost-all-dev)

# Fill in path for TCLAP
TCLAP_INCL		= ./include

# Order of the CRF model to be trained and applied
MODEL_ORDER	= 1


CRF_MODEL_INCLUDES	= include/SimpleLinearCRFModel.hpp include/CRFTypedefs.hpp include/StringUnsignedMapper.hpp
CRF_TRAINING_INCLUDES	= $(CRF_MODEL_INCLUDES) include/CRFTrainingCorpus.hpp include/CRFDecoder.hpp \
                          include/CRFTraining.hpp include/AveragedPerceptronCRFTrainer.hpp
NER_ANNOTATE_INCLUDES	= include/NERFeatureExtractor.hpp include/NERConfiguration.hpp include/AsyncTokenizer.hpp \
                          include/TokenWithTag.hpp include/tokenizer.hpp include/next_token.cpp include/WDAWG.hpp
CRF_APPLY_INCLUDES	= include/CRFApplier.hpp $(CRF_MODEL_INCLUDES) $(NER_ANNOTATE_INCLUDES) \
                          include/CRFDecoder.hpp include/NEROutputters.hpp 


# Binaries
NER_ANNOTATE	= ner-annotate
CRF_TRAIN    	= crf-train
CRF_APPLY	= crf-apply
CRF_CONVERT	= crf-convert

CL_OPTIONS	= -I $(TCLAP_INCL) -O3 -std=c++11 -DMODEL_ORDER=$(MODEL_ORDER)
#CC_COMP        = clang++-3.5
CC_COMP         = g++


all : $(NER_ANNOTATE) $(CRF_TRAIN) $(CRF_APPLY) $(CRF_CONVERT)

install: all
	sudo cp $(NER_ANNOTATE) $(CRF_TRAIN) $(CRF_APPLY) $(CRF_CONVERT) /usr/local/bin


$(NER_ANNOTATE) : src/ner-annotate.cpp $(NER_ANNOTATE_INCLUDES) include/ner-helpers.hpp
	$(CC_COMP) $(CL_OPTIONS) -o $(NER_ANNOTATE) src/ner-annotate.cpp


$(CRF_TRAIN) : src/crf-train.cpp $(CRF_TRAINING_INCLUDES)
	$(CC_COMP) $(CL_OPTIONS) -o $(CRF_TRAIN) src/crf-train.cpp


$(CRF_APPLY) : src/crf-apply.cpp $(CRF_APPLY_INCLUDES)
	$(CC_COMP) $(CL_OPTIONS) -o $(CRF_APPLY) src/crf-apply.cpp


$(CRF_CONVERT): src/crf-convert.cpp $(CRF_MODEL_INCLUDES)
	$(CC_COMP) $(CL_OPTIONS) -o $(CRF_CONVERT) src/crf-convert.cpp

clean:
	rm -f *.o $(NER_ANNOTATE) $(CRF_TRAIN) $(CRF_APPLY) $(CRF_CONVERT)

